"""
Django settings for jigyasa project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

print("I am in " + str(BASE_DIR))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sym*i6d+*275y!9(b^%qffdmi3zi&&wgs@(p2w$5b5u!t_k4os'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0','192.168.13.87','10.152.2.137']


FILE_TO_URL_MAPPING  = {'Screen Reader Information.csv': 'https://maharashtra.nic.in/help/',
 'Plug-in for alternate document types.csv': 'https://maharashtra.nic.in/help/',
 'SIO (State Informatics Officer).csv': 'https://maharashtra.nic.in/directory/',
 'Maharashtra State Centre, Mumbai.csv': 'https://maharashtra.nic.in/directory/',
 'Ahmadnagar.csv': 'https://maharashtra.nic.in/directory/',
 'Akola.csv': 'https://maharashtra.nic.in/directory/',
 'Amravati.csv': 'https://maharashtra.nic.in/directory/',
 'Aurangabad.csv': 'https://maharashtra.nic.in/directory/',
 'Beed.csv': 'https://maharashtra.nic.in/directory/',
 'Bhandara.csv': 'https://maharashtra.nic.in/directory/',
 'Buldana.csv': 'https://maharashtra.nic.in/directory/',
 'Chandrapur.csv': 'https://maharashtra.nic.in/directory/',
 'Dhule.csv': 'https://maharashtra.nic.in/directory/',
'District Centres (final test).csv': 'https://maharashtra.nic.in/district-centres/',
 'Gadchiroli.csv': 'https://maharashtra.nic.in/directory/',
 'Gondia.csv': 'https://maharashtra.nic.in/directory/',
 'Hingoli.csv': 'https://maharashtra.nic.in/directory/',
 'Jalgaon.csv': 'https://maharashtra.nic.in/directory/',
 'Jalna.csv': 'https://maharashtra.nic.in/directory/',
 'Kolhapur.csv': 'https://maharashtra.nic.in/directory/',
 'Mumbai.csv': 'https://maharashtra.nic.in/directory/',
 'Mumbai Suburban (Bandra).csv': 'https://maharashtra.nic.in/directory/',
 'Nagpur.csv': 'https://maharashtra.nic.in/directory/',
 'Nanded.csv': 'https://maharashtra.nic.in/directory/',
 'Nandurbar.csv': 'https://maharashtra.nic.in/directory/',
 'Nasik.csv': 'https://maharashtra.nic.in/directory/',
 'Osmanabad.csv': 'https://maharashtra.nic.in/directory/',
 'Palghar.csv': 'https://maharashtra.nic.in/directory/',
 'Parbhani.csv': 'https://maharashtra.nic.in/directory/',
 'Pune District.csv': 'https://maharashtra.nic.in/directory/',
'Reporting_officer.csv': 'https://maharashtra.nic.in/organization-structure/',
 'Raigad.csv': 'https://maharashtra.nic.in/directory/',
 'Ratnagiri.csv': 'https://maharashtra.nic.in/directory/',
 'Sangli.csv': 'https://maharashtra.nic.in/directory/',
 'Satara.csv': 'https://maharashtra.nic.in/directory/',
 'Sindhu Durg.csv': 'https://maharashtra.nic.in/directory/',
 'Solapur.csv': 'https://maharashtra.nic.in/directory/',
 'Thane.csv': 'https://maharashtra.nic.in/directory/',
 'Wardha.csv': 'https://maharashtra.nic.in/directory/',
 'Washim.csv': 'https://maharashtra.nic.in/directory/',
 'Yavatmal.csv': 'https://maharashtra.nic.in/directory/',
 'APPELLATE AUTHORITY.csv': 'https://maharashtra.nic.in/rti/',
 'PUBLIC INFORMATION OFFICERS ( PIO ).csv': 'https://maharashtra.nic.in/rti/'}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'jigyasa_chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jigyasa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jigyasa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


from llama_index.core.postprocessor import SentenceTransformerRerank
from llama_index.core import SimpleDirectoryReader
from llama_index.core import VectorStoreIndex
from llama_index.llms.ollama import Ollama
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings
from llama_index.readers.web import SimpleWebPageReader
from llama_index.readers.file import (
    DocxReader,
    HWPReader,
    PDFReader,
    EpubReader,
    FlatReader,
    HTMLTagReader,
    ImageCaptionReader,
    ImageReader,
    ImageVisionLLMReader,
    IPYNBReader,
    MarkdownReader,
    MboxReader,
    PptxReader,
    PandasCSVReader,
    VideoAudioReader,
    UnstructuredReader,
    PyMuPDFReader,
    ImageTabularChartReader,
    XMLReader,
    PagedCSVReader,
    CSVReader,
    RTFReader,
)
from llama_index.core import (
    load_index_from_storage,
    StorageContext,
)

Settings.llm = Ollama(model="llama3", temperature=0, request_timeout=500.0)
Settings.embed_model = HuggingFaceEmbedding(model_name="Alibaba-NLP/gte-large-en-v1.5", trust_remote_code=True)
        #persist_dir = "/content/combine_index"
#persist_dir = "C:\\Users\\USER\\Desktop\\LLM_Chatbot\\ollama-QA-gen\\chat_url\\combined_index"

persist_dir = "C:\\Users\\USER\\Desktop\\LLM_Chatbot\\ollama-QA-gen\\chat_url\\combined_index_v1\\"


storage_context = StorageContext.from_defaults(persist_dir=persist_dir)
INDEX_INSTANCE = load_index_from_storage(storage_context)

rerank = SentenceTransformerRerank(model="BAAI/bge-reranker-large", top_n=3)



from llama_index.core.storage.chat_store import SimpleChatStore
from llama_index.core.memory import ChatMemoryBuffer

# Load the chat store from the file
loaded_chat_store1 = SimpleChatStore.from_persist_path(
    persist_path="C:\\Users\\USER\\Desktop\\LLM_Chatbot\\ollama-QA-gen\\chat_url\\chat_store_v2.pkl"
)

chat_memory1 = ChatMemoryBuffer.from_defaults(
    token_limit=30000,
    chat_store=loaded_chat_store1,
    chat_store_key="user1",

)


# Initialize the chat engine
CHAT_ENGINE = INDEX_INSTANCE.as_chat_engine(
    chat_mode="context",
    system_prompt="You are a helpful AI assistant. You are expert in retrieving the answer for the user input based on the provided context. Important note: You must not mention any file name or file path in your response.",
    memory=chat_memory1, verbose = True,similarity_top_k=10, node_postprocessors=[rerank]
)




#QUERY_ENGINE = INDEX_INSTANCE.as_query_engine(similarity_top_k=3, node_postprocessors=[rerank])


